# extends:
#     [
#         'stylelint-config-standard',
#         'stylelint-prettier/recommended',
#         'stylelint-config-standard-scss',
#     ]
# rules: ['import-notation': 'string',
# 'color-function-notation': "modern"
# ]

extends:
    - 'stylelint-config-standard'
    - 'stylelint-prettier/recommended'
    - 'stylelint-config-standard-scss'
rules:
    import-notation: 'string'
    color-function-notation: 'modern'
    at-rule-empty-line-before: 'always'
    selector-class-pattern: '^([a-z][a-zA-Z0-9]*)(-[a-z][a-zA-Z0-9]*)?(__[a-z][a-zA-Z0-9]*)?$'
